/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
    
    @Test public void testContentAppAGreeting() {
        App classUnderTest = new App();
		assertEquals("Hi Hello world.", classUnderTest.getGreeting();
    }
}
